name: moderators_list
description: "VimeWorld Moderators List"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  extra_pedantic: ^4.0.0

flutter:
  uses-material-design: true